### ISSUE TITLE
Complete migration to asyncio

### ISSUE THREAD

**Issue by pagekite** [pagekite/upagekite#13]
The current asyncio compatibility is incomplete; most socket operations happen on raw sockets and upagekite interleaves its own poll()-based event loop with that of asyncio.

This is useful because it facilitates the current, simple API for developing dynamic web apps.

But it's also inefficient and introduces some lag/jitter which it would be nice to eliminate or minimize.

**Comment by BjarniRunar** [comment]
I think this may actually be a wontfix, at least or now. The asyncio support on micropython is so limited, that it seems unclear to me how to do some of the lower level ops I need. And TLS support is also problematic.

There are areas where we could benefit from using asyncio more effectively, but it's not urgent. Closing for now.
